Repository Informo/specs, pull requests merged in 2018-11, with the labels that each got.

#10 Removed content/matrix/ folder
  config.toml
  content/matrix/_index.md
  content/matrix/events.md
  content/matrix/usage.md
  content/matrix/users.md
Labels: scsp:review, type:typo

#2 Phase 2: Nodes
  content/information-distribution/node.md
Labels: scsp:review, type:behaviour

#4 Shorter SCSP behaviour review duration
  content/introduction/scsp.md
Labels: scsp:review, type:behaviour

#8 Matrix event signing
  content/information-distribution/article.md
  content/information-distribution/signature.md
  content/trust-management/trust-authority.md
Labels: scsp:review, type:behaviour

#9 `network.informo.article` matrix event
  content/information-distribution/article.md
Labels: scsp:review, type:behaviour

#12 Update articles's intro made out of date by SCS #9
  content/information-distribution/article.md
Labels: scsp:pending, type:typo

#13 Remove the 'scsp:review' label for typo SCS
  content/introduction/scsp.md
Labels: scsp:review, type:behaviour
